### PR TITLE
tag posts with ownership information for post filtering

### LINKED ISSUE #52: add "who posted this" classes to the React components
Right now a post by, for instance, giphy_bot does not indicate that its `<div>` belongs to giphy_bot in any meaningful way, making it impossible to filter noise out of a chat log. It would be most useful if post divs got a `className={...}` that contained the posting user's mattermost-name

### PR DESCRIPTION
**Pull request by Pomax**
This adds a `post__wrapper` class to user posts, with the owning username as class too, to allow custom post filtering using simple CSS selectors.

(fixes https://github.com/mozilla/mattermoz/issues/52)

### CODE REVIEW

**Comment by alanmoo** [comment]
LGTM, @cadecairos what's the status of PR's submitted here? If we update to a newer version of Mattermost and these features haven't been merged upstream, is it easy enough to rebase them?

**Comment by cadecairos** [comment]
For every new major release, we're probably looking at some manual work.

**Comment by alanmoo** [comment]
So it's probably best to get these upstream when possible. @pomax this is effectively a quick way to enable user muting, correct? Am I right in guessing that a proper implementation of muting is the feature you'd eventually rather merge upstream than this?

**Comment by Pomax** [comment]
You are both right and wrong. Muting is the ultimate goal, but I am highly unlikely to write the full UI and underwater code to achieve that. I'm a great fan of "land small things fast" so that you can keep building - that way if you stop building, you still have all the foundations available for someone else to work on top of. So ultimate muting would be great, but before we get there, this is equally great in the functionality it unlocks.

**Comment by alanmoo** [comment]
Good point. Merge away, and feel free to submit a PR upstream to Mattermost (though be aware of their [guidelines](http://docs.mattermost.com/developer/contribution-guide.html))

**Comment by Pomax** [comment]
yeah I'm going to have to get @simonwex or someone else to file that PR for me against mattermost (unless they add an org-CLA, in which case we can file it as "mozilla")... I have strong principled objections to CLAs that demand information that exclude people who don't have a phone or stable home/mailing address.

**Comment by alanmoo** [comment]
Heh...I've been struggling with that "home address" one for a while now.

**Comment by alanmoo** [comment]
@Pomax  If you file the feature request in their forums and get an official ticket for it (with the PLT-####), I can submit the PR.

**Comment by Pomax** [comment]
that, I can certainly do. http://forum.mattermost.org/t/marking-posts-with-the-user-who-posted-it/912

**Pull request merged**
